<!DOCTYPE html>
<html>
<head>    
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=9" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<title>Exemplo de Página</title>
<!-- exemplo de instância para arquivos css, js e img -> começar com "/" para buscar na raiz, se o projeto estiver em um diretório, ele deverá estar como subdomínio na url -->
<link href="/assets/css/style.css" rel="stylesheet" type="text/css"/>
</head>
<body>
 <h1>Hello World !</h1>
</body>
</html>