<!DOCTYPE html>
<html>
<head>    
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=9" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<title>Exemplo de Página</title>
<!-- exemplo de instância para arquivos css, js e img -> começar com "/" para buscar na raiz, se o projeto estiver em um diretório, ele deverá estar como subdomínio na url -->
<link href="/assets/css/style.css" rel="stylesheet" class="kenjsHREF" type="text/css"/>
</head>
<body>
<h1>Hellow World !</h1>
<p><img src="/assets/images/logo-cf.png" class="kenjsSRC" alt="" /></p>
<script type="text/javascript" src="<?php echo ROOT;?>/assets/js/jquery.js"></script>
<script type="text/javascript" src="<?php echo ROOT;?>/assets/js/materialize.js"></script>
<script type="text/javascript" src="<?php echo ROOT;?>/assets/js/kenjs.js"></script>
</body>
</html>