<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=9" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Exemplo de Página</title>
    <!-- exemplo de instância para arquivos css, js e img -> começar com "/" para buscar na raiz, se o projeto estiver em um diretório, ele deverá estar como subdomínio na url -->
    <link href="<?php echo $this->_raiz;?>/assets/css/style.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<h1>Hello<?php echo $this->_raiz;?> Test !</h1>
<p><img src="<?php echo $this->_raiz;?>/assets/images/logo-cf.png" alt="" /></p>
<span></span>
<script>
    var url = window.location.pathname;
    var exp = url.split("/");
    var domain = exp[1];
    console.log(domain);
</script>
</body>
</html>